# Generated by Django 5.2.4 on 2025-07-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profiles'),
        ),
    ]
