# Generated by Django 5.2.4 on 2025-07-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_userinfo_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bio',
            field=models.TextField(default='not provided'),
        ),
    ]
